import { cva } from 'class-variance-authority';

const buttonStyles = cva(
  [
    'inline-flex',
    'items-center',
    'justify-center',
    'enabled:cursor-pointer',
    'focus:outline-none',
    'transition',
    'duration-150',
    'ease-in-out',
    'data-[has-left-element=true]:rounded-l-none',
    'data-[has-right-element=true]:rounded-r-none',
    'data-[has-left-element=true]:h-auto',
    'data-[has-right-element=true]:h-auto',
  ],
  {
    variants: {
      tone: {
        solid: ['border'],
        light: ['border', 'border-transparent'],
        transparent: ['border', 'border-transparent', 'bg-transparent'],
        outline: ['border', 'bg-white', 'disabled:hover:bg-transparent'],
      },
      color: {
        white: ['focus:ring-gray-50'],
        blue: ['focus:ring-blue-50'],
        red: ['focus:ring-red-50'],
        green: ['focus:ring-green-50'],
        yellow: ['focus:ring-yellow-50'],
        purple: ['focus:ring-purple-50'],
        gray: ['focus:ring-gray-50'],
        dark: ['focus:ring-gray-200'],
        black: ['focus:ring-gray-300'],
      },
      size: {
        xs: ['text-xs'],
        sm: ['text-sm', 'h-8'],
        md: ['text-sm', 'h-10'],
        lg: ['text-base', 'h-12'],
      },
      radius: {
        none: ['rounded-none'],
        sm: ['rounded-sm'],
        base: ['rounded'],
        md: ['rounded-md'],
        lg: ['rounded-lg'],
        full: ['rounded-full'],
      },
      animation: {
        none: [''],
        pulse: ['animate-pulse'],
        bounce: ['animate-bounce'],
      },
      shadow: {
        none: ['shadow-none'],
        sm: ['shadow-sm'],
        base: ['shadow'],
        md: ['shadow-md'],
        lg: ['shadow-lg'],
        xl: ['shadow-xl'],
      },
      shadowColor: {
        none: [''],
        white: ['shadow-gray-200/50 hover:shadow-gray-200/60'],
        blue: ['shadow-blue-500/50', 'hover:shadow-blue-500/60'],
        red: ['shadow-red-500/50 hover:shadow-red-500/60'],
        green: ['shadow-green-500/50 hover:shadow-green-500/60'],
        yellow: ['shadow-yellow-500/50 hover:shadow-yellow-500/60'],
        purple: ['shadow-purple-500/50 hover:shadow-purple-500/60'],
        gray: ['shadow-gray-400/50 hover:shadow-gray-400/60'],
        dark: ['shadow-gray-600/50 hover:shadow-gray-600/60'],
        black: ['shadow-gray-800/50 hover:shadow-gray-800/60'],
      },
      icon: {
        true: [],
        false: [],
      },
      loading: {
        true: ['cursor-progress'],
        false: [],
      },
      disabled: {
        true: ['cursor-not-allowed'],
        false: [],
      },
      withRing: {
        true: ['focus:ring', 'focus:ring-offset-0'],
        false: ['focus:ring-0'],
      },
    },
    defaultVariants: {
      tone: 'solid',
      color: 'blue',
    },
    compoundVariants: [
      {
        icon: false,
        size: 'xs',
        className: ['px-2', 'h-6'],
      },
      {
        icon: false,
        size: 'sm',
        className: ['px-2.5', 'h-8'],
      },
      {
        icon: false,
        size: 'md',
        className: ['px-4', 'h-10'],
      },
      {
        icon: false,
        size: 'lg',
        className: ['px-5', 'h-12'],
      },
      {
        icon: true,
        size: 'xs',
        className: ['w-6', 'h-6'],
      },
      {
        icon: true,
        size: 'sm',
        className: ['w-8', 'h-8'],
      },
      {
        icon: true,
        size: 'md',
        className: ['w-10', 'h-10'],
      },
      {
        icon: true,
        size: 'lg',
        className: ['w-12', 'h-12'],
      },
      {
        tone: 'solid',
        color: ['blue', 'red', 'green', 'yellow', 'purple', 'gray', 'dark', 'black'],
        className: ['border-transparent'],
      },
      {
        tone: 'light',
        color: ['blue', 'red', 'green', 'yellow', 'purple', 'dark', 'black'],
        className: ['focus:text-white'],
      },
      {
        tone: 'outline',
        color: ['blue', 'red', 'green', 'yellow', 'purple', 'dark', 'black'],
        className: ['focus:text-white', 'hover:text-white'],
      },
      {
        tone: 'solid',
        color: 'white',
        className: [
          'text-gray-800',
          'border-gray-100',
          'bg-white',
          'focus:bg-gray-50',
          'hover:bg-gray-50',
          'active:bg-gray-100',
          'disabled:bg-gray-50/50',
          'disabled:hover:bg-gray-50',
        ],
      },
      {
        tone: 'solid',
        color: 'blue',
        className: [
          'text-white',
          'bg-blue-500',
          'focus:bg-blue-600',
          'hover:bg-blue-600',
          'active:bg-blue-700',
          'disabled:bg-blue-300',
          'disabled:hover:bg-blue-300',
        ],
      },
      {
        tone: 'solid',
        color: 'red',
        className: [
          'text-white',
          'bg-red-500',
          'focus:bg-red-600',
          'hover:bg-red-600',
          'active:bg-red-700',
          'disabled:bg-red-300',
          'disabled:hover:bg-red-300',
        ],
      },
      {
        tone: 'solid',
        color: 'green',
        className: [
          'text-white',
          'bg-green-500',
          'focus:bg-green-600',
          'hover:bg-green-600',
          'active:bg-green-700',
          'disabled:bg-green-300',
          'disabled:hover:bg-green-300',
        ],
      },
      {
        tone: 'solid',
        color: 'yellow',
        className: [
          'text-white',
          'bg-yellow-400',
          'focus:bg-yellow-500',
          'hover:bg-yellow-500',
          'active:bg-yellow-600',
          'disabled:bg-yellow-200',
          'disabled:hover:bg-yellow-200',
        ],
      },
      {
        tone: 'solid',
        color: 'purple',
        className: [
          'text-white',
          'bg-purple-500',
          'focus:bg-purple-600',
          'hover:bg-purple-600',
          'active:bg-purple-700',
          'disabled:bg-purple-300',
          'disabled:hover:bg-purple-300',
        ],
      },
      {
        tone: 'solid',
        color: 'gray',
        className: [
          'text-gray-800',
          'bg-gray-200',
          'focus:bg-gray-300',
          'hover:bg-gray-300',
          'active:bg-gray-400',
          'disabled:bg-gray-100',
          'disabled:hover:bg-gray-100',
          'disabled:text-gray-400',
        ],
      },
      {
        tone: 'solid',
        color: 'dark',
        className: [
          'text-white',
          'bg-gray-700',
          'focus:bg-gray-800',
          'hover:bg-gray-800',
          'active:bg-gray-900',
          'disabled:bg-gray-500',
          'disabled:hover:bg-gray-500',
        ],
      },
      {
        tone: 'solid',
        color: 'black',
        className: ['text-white', 'bg-black', 'disabled:bg-gray-800'],
      },
      {
        tone: 'light',
        color: 'white',
        className: [
          'text-gray-800',
          'hover:text-gray-900',
          'border-gray-100',
          'bg-white',
          'disabled:bg-gray-50/50',
          'disabled:hover:bg-gray-50',
        ],
      },
      {
        tone: 'light',
        color: 'blue',
        className: [
          'text-blue-500',
          'hover:text-white',
          'disabled:text-blue-400',
          'disabled:hover:text-blue-400',
          'bg-blue-50/50',
          'hover:bg-blue-500',
          'focus:bg-blue-500',
          'active:bg-blue-600',
          'disabled:bg-blue-50',
          'disabled:hover:bg-blue-50',
        ],
      },
      {
        tone: 'light',
        color: 'red',
        className: [
          'text-red-500',
          'hover:text-white',
          'disabled:text-red-400',
          'disabled:hover:text-red-400',
          'bg-red-50/50',
          'hover:bg-red-500',
          'focus:bg-red-500',
          'active:bg-red-600',
          'disabled:bg-red-50',
          'disabled:hover:bg-red-50',
        ],
      },
      {
        tone: 'light',
        color: 'green',
        className: [
          'text-green-500',
          'hover:text-white',
          'disabled:text-green-400',
          'disabled:hover:text-green-400',
          'bg-green-50/50',
          'hover:bg-green-500',
          'focus:bg-green-500',
          'active:bg-green-600',
          'disabled:bg-green-50',
          'disabled:hover:bg-green-50',
        ],
      },
      {
        tone: 'light',
        color: 'yellow',
        className: [
          'text-yellow-500',
          'hover:text-white',
          'disabled:text-yellow-400',
          'disabled:hover:text-yellow-400',
          'bg-yellow-50/50',
          'hover:bg-yellow-500',
          'focus:bg-yellow-500',
          'active:bg-yellow-600',
          'disabled:bg-yellow-50',
          'disabled:hover:bg-yellow-50',
        ],
      },
      {
        tone: 'light',
        color: 'purple',
        className: [
          'text-purple-500',
          'hover:text-white',
          'disabled:text-purple-400',
          'disabled:hover:text-purple-400',
          'bg-purple-50/50',
          'hover:bg-purple-500',
          'focus:bg-purple-500',
          'active:bg-purple-600',
          'disabled:bg-purple-50',
          'disabled:hover:bg-purple-50',
        ],
      },
      {
        tone: 'light',
        color: 'gray',
        className: [
          'text-gray-600',
          'hover:text-white',
          'focus:text-gray-700',
          'disabled:text-gray-700',
          'disabled:hover:text-gray-500',
          'bg-gray-50/50',
          'hover:bg-gray-300',
          'focus:bg-gray-300',
          'active:bg-gray-400',
          'disabled:bg-gray-50',
          'disabled:hover:bg-gray-50',
        ],
      },
      {
        tone: 'light',
        color: 'dark',
        className: [
          'text-gray-800',
          'hover:text-white',
          'disabled:text-gray-500',
          'disabled:hover:text-gray-500',
          'bg-gray-200/50',
          'hover:bg-gray-700',
          'focus:bg-gray-700',
          'active:bg-gray-800',
          'disabled:bg-gray-100',
          'disabled:hover:bg-gray-100',
        ],
      },
      {
        tone: 'light',
        color: 'black',
        className: [
          'text-gray-800',
          'hover:text-white',
          'disabled:text-gray-500',
          'disabled:hover:text-gray-500',
          'bg-gray-400/50',
          'hover:bg-gray-900',
          'focus:bg-gray-900',
          'active:bg-black',
          'disabled:bg-gray-200',
          'disabled:hover:bg-gray-200',
        ],
      },
      {
        tone: 'transparent',
        color: 'blue',
        className: [
          'text-blue-500',
          'disabled:text-blue-200',
          'hover:bg-blue-50/50',
          'focus:bg-blue-50/50',
          'active:bg-blue-100/50',
        ],
      },
      {
        tone: 'transparent',
        color: 'red',
        className: [
          'text-red-500',
          'disabled:text-red-200',
          'hover:bg-red-50/50',
          'focus:bg-red-50/50',
          'active:bg-red-100/50',
        ],
      },
      {
        tone: 'transparent',
        color: 'green',
        className: [
          'text-green-500',
          'disabled:text-green-200',
          'hover:bg-green-50/50',
          'focus:bg-green-50/50',
          'active:bg-green-100/50',
        ],
      },
      {
        tone: 'transparent',
        color: 'yellow',
        className: [
          'text-yellow-400',
          'disabled:text-yellow-100',
          'hover:bg-yellow-50/50',
          'focus:bg-yellow-50/50',
          'active:bg-yellow-100/50',
        ],
      },
      {
        tone: 'transparent',
        color: 'purple',
        className: [
          'text-purple-500',
          'disabled:text-purple-200',
          'hover:bg-purple-50/50',
          'focus:bg-purple-50/50',
          'active:bg-purple-100/50',
        ],
      },
      {
        tone: 'transparent',
        color: 'gray',
        className: [
          'text-gray-500',
          'disabled:text-gray-200',
          'hover:bg-gray-50/50',
          'focus:bg-gray-50/50',
          'active:bg-gray-100/50',
        ],
      },
      {
        tone: 'transparent',
        color: 'dark',
        className: [
          'text-gray-800',
          'disabled:text-gray-500',
          'hover:bg-gray-200/50',
          'focus:bg-gray-200/50',
          'active:bg-gray-300/50',
        ],
      },
      {
        tone: 'transparent',
        color: 'black',
        className: [
          'text-black',
          'disabled:text-gray-700',
          'hover:bg-gray-400/50',
          'focus:bg-gray-400/50',
          'active:bg-gray-500/50',
        ],
      },
      {
        tone: 'outline',
        color: 'blue',
        className: [
          'text-blue-500',
          'disabled:text-blue-300',
          'disabled:hover:text-blue-300',
          'hover:bg-blue-500',
          'focus:bg-blue-500',
          'active:bg-blue-600',
          'border-blue-500',
          'disabled:border-blue-300',
        ],
      },
      {
        tone: 'outline',
        color: 'red',
        className: [
          'text-red-500',
          'disabled:text-red-300',
          'disabled:hover:text-red-300',
          'hover:bg-red-500',
          'focus:bg-red-500',
          'active:bg-red-600',
          'border-red-500',
          'disabled:border-red-300',
        ],
      },
      {
        tone: 'outline',
        color: 'green',
        className: [
          'text-green-500',
          'disabled:text-green-300',
          'disabled:hover:text-green-300',
          'hover:bg-green-500',
          'focus:bg-green-500',
          'active:bg-green-600',
          'border-green-500',
          'disabled:border-green-300',
        ],
      },
      {
        tone: 'outline',
        color: 'yellow',
        className: [
          'text-yellow-500',
          'disabled:text-yellow-300',
          'disabled:hover:text-yellow-300',
          'hover:bg-yellow-500',
          'focus:bg-yellow-500',
          'active:bg-yellow-600',
          'border-yellow-500',
          'disabled:border-yellow-300',
        ],
      },
      {
        tone: 'outline',
        color: 'purple',
        className: [
          'text-purple-500',
          'disabled:text-purple-300',
          'disabled:hover:text-purple-300',
          'hover:bg-purple-500',
          'focus:bg-purple-500',
          'active:bg-purple-600',
          'border-purple-500',
          'disabled:border-purple-300',
        ],
      },
      {
        tone: 'outline',
        color: 'gray',
        className: [
          'text-gray-500',
          'hover:text-gray-500',
          'focus:text-gray-500',
          'disabled:text-gray-300',
          'disabled:hover:text-gray-300',
          'hover:bg-gray-200',
          'focus:bg-gray-200',
          'active:bg-gray-300',
          'border-gray-200',
          'disabled:border-gray-300',
        ],
      },
      {
        tone: 'outline',
        color: 'dark',
        className: [
          'text-gray-500',
          'disabled:text-gray-300',
          'disabled:hover:text-gray-300',
          'hover:bg-gray-700',
          'focus:bg-gray-700',
          'active:bg-gray-800',
          'border-gray-700',
          'disabled:border-gray-300',
        ],
      },
      {
        tone: 'outline',
        color: 'black',
        className: [
          'text-black',
          'disabled:text-gray-500',
          'disabled:hover:text-gray-500',
          'hover:bg-black',
          'focus:bg-black',
          'active:bg-black',
          'border-black',
          'disabled:border-gray-500',
        ],
      },
    ],
  }
);

const chevronStyles = cva([], {
  variants: {
    open: {
      true: [],
      false: [],
    },
    chevronRotation: {
      true: [],
      false: [],
    },
    size: {
      xs: ['w-3', 'h-3', 'ml-1'],
      sm: ['w-4', 'h-4', 'ml-2'],
      md: ['w-4', 'h-4', 'ml-2', '-mr-1'],
      lg: ['w-5', 'h-5', 'ml-2', '-mr-1.5'],
    },
  },
  compoundVariants: [
    {
      chevronRotation: true,
      className: ['transition', 'transform', 'duration-300', 'ease-in-out'],
    },
    {
      open: true,
      chevronRotation: true,
      className: ['-rotate-180'],
    },
  ],
});

const buttonSpinnerStyles = cva(['-ml-1', 'mr-2', 'animate-spin'], {
  variants: {
    size: {
      xs: ['w-3', 'h-3'],
      sm: ['w-5', 'h-5'],
      md: ['w-6', 'h-6'],
      lg: ['w-8', 'h-8'],
    },
  },
});

export { buttonStyles, chevronStyles, buttonSpinnerStyles };
